import type { Metadata } from "next";
import "./globals.css";
import { NavBar } from "@/components";
import { getSession } from "@/helpers/session";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getSession();
  console.log("user", user);
  return (
    <html lang="pt-BR">
      <body className="bg-slate-890 text-slate-300">
        <NavBar user={user}/>
        {children}
      </body>
    </html>
  );
}
